name: Test

on: [push, pull_request]

jobs:
  snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plan: [basic, pro, max]
      fail-fast: true
      max-parallel: 3
    outputs:
      snapshot_basic: ${{ steps.create-snapshot.outputs.snapshot_basic }}
      snapshot_pro: ${{ steps.create-snapshot.outputs.snapshot_pro }}
      snapshot_max: ${{ steps.create-snapshot.outputs.snapshot_max }}
    steps:
      - name: Run ${{ matrix.plan }} tests
        run: |
          SNAPSHOT="snapshot_${{ matrix.plan }}"
          echo "Running tests for plan: ${{ matrix.plan }}"
          echo "snapshot_${{ matrix.plan }}=snapshot_data_for_${{ matrix.plan }}" >> $GITHUB_OUTPUT
  test:
    needs: snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Use snapshot_basic
        run: echo "Using snapshot: ${{ jobs.snapshots.outputs.snapshot_basic }}"
      - name: Use snapshot_pro
        run: echo "Using snapshot: ${{ jobs.snapshots.outputs.snapshot_pro }}"
      - name: Use snapshot_max
        run: echo "Using snapshot: ${{ jobs.snapshots.outputs.snapshot_max }}"
